import {Player} from '../interfaces/playerTeamInterfaces';

const freePlayersDefault: Player[] = [
  {
    name: 'Iceberg',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.301,
      accuracy: 0.595,
      sprayControl: 0.657,
      flicksControl: 0.686,
      nades: 0.791,
      tactics: 0.555,
    },
  },
  {
    name: 'M1ner',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.486,
      accuracy: 0.619,
      sprayControl: 0.345,
      flicksControl: 0.428,
      nades: 0.855,
      tactics: 0.334,
    },
  },
  {
    name: 'Vampire',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.282,
      accuracy: 0.492,
      sprayControl: 0.713,
      flicksControl: 0.851,
      nades: 0.599,
      tactics: 0.699,
    },
  },
  {
    name: 'Bear',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.229,
      accuracy: 0.472,
      sprayControl: 0.345,
      flicksControl: 0.875,
      nades: 0.763,
      tactics: 0.607,
    },
  },
  {
    name: 'Fenix',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.346,
      accuracy: 0.728,
      sprayControl: 0.85,
      flicksControl: 0.554,
      nades: 0.378,
      tactics: 0.685,
    },
  },
  {
    name: 'Riot',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.304,
      accuracy: 0.368,
      sprayControl: 0.767,
      flicksControl: 0.48,
      nades: 0.409,
      tactics: 0.737,
    },
  },
  {
    name: 'Rebel',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.311,
      accuracy: 0.327,
      sprayControl: 0.532,
      flicksControl: 0.58,
      nades: 0.677,
      tactics: 0.733,
    },
  },
  {
    name: 'Lynx',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.246,
      accuracy: 0.678,
      sprayControl: 0.837,
      flicksControl: 0.641,
      nades: 0.482,
      tactics: 0.622,
    },
  },
  {
    name: 'Shart',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.395,
      accuracy: 0.61,
      sprayControl: 0.592,
      flicksControl: 0.892,
      nades: 0.853,
      tactics: 0.752,
    },
  },
  {
    name: 'Whip',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.225,
      accuracy: 0.578,
      sprayControl: 0.436,
      flicksControl: 0.659,
      nades: 0.389,
      tactics: 0.851,
    },
  },
  {
    name: 'TheBest',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.332,
      accuracy: 0.864,
      sprayControl: 0.548,
      flicksControl: 0.518,
      nades: 0.654,
      tactics: 0.654,
    },
  },
  {
    name: 'Launcher',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.347,
      accuracy: 0.323,
      sprayControl: 0.356,
      flicksControl: 0.736,
      nades: 0.746,
      tactics: 0.561,
    },
  },
  {
    name: 'Sky',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.373,
      accuracy: 0.719,
      sprayControl: 0.59,
      flicksControl: 0.878,
      nades: 0.881,
      tactics: 0.38,
    },
  },
  {
    name: 'Bell',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.241,
      accuracy: 0.584,
      sprayControl: 0.797,
      flicksControl: 0.665,
      nades: 0.5,
      tactics: 0.8,
    },
  },
  {
    name: 'Brocoli',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.255,
      accuracy: 0.539,
      sprayControl: 0.679,
      flicksControl: 0.584,
      nades: 0.426,
      tactics: 0.877,
    },
  },
  {
    name: 'Drill',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.362,
      accuracy: 0.435,
      sprayControl: 0.576,
      flicksControl: 0.347,
      nades: 0.791,
      tactics: 0.586,
    },
  },
  {
    name: 'Catt',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.272,
      accuracy: 0.479,
      sprayControl: 0.552,
      flicksControl: 0.466,
      nades: 0.804,
      tactics: 0.468,
    },
  },
  {
    name: 'Girkiy',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.48,
      accuracy: 0.864,
      sprayControl: 0.472,
      flicksControl: 0.81,
      nades: 0.764,
      tactics: 0.438,
    },
  },
  {
    name: 'L0ud',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.362,
      accuracy: 0.542,
      sprayControl: 0.452,
      flicksControl: 0.328,
      nades: 0.461,
      tactics: 0.318,
    },
  },
  {
    name: 'Silent',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.442,
      accuracy: 0.838,
      sprayControl: 0.504,
      flicksControl: 0.446,
      nades: 0.846,
      tactics: 0.584,
    },
  },
  {
    name: 'Bruce',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.401,
      accuracy: 0.371,
      sprayControl: 0.478,
      flicksControl: 0.888,
      nades: 0.514,
      tactics: 0.367,
    },
  },
  {
    name: 'Bean',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.327,
      accuracy: 0.549,
      sprayControl: 0.318,
      flicksControl: 0.653,
      nades: 0.349,
      tactics: 0.594,
    },
  },
  {
    name: 'Fremen',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.469,
      accuracy: 0.877,
      sprayControl: 0.835,
      flicksControl: 0.64,
      nades: 0.823,
      tactics: 0.463,
    },
  },
  {
    name: 'Snake',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.413,
      accuracy: 0.594,
      sprayControl: 0.649,
      flicksControl: 0.672,
      nades: 0.454,
      tactics: 0.823,
    },
  },
  {
    name: 'IKill',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.242,
      accuracy: 0.558,
      sprayControl: 0.473,
      flicksControl: 0.581,
      nades: 0.314,
      tactics: 0.402,
    },
  },
  {
    name: 'Smoke',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.329,
      accuracy: 0.558,
      sprayControl: 0.509,
      flicksControl: 0.509,
      nades: 0.871,
      tactics: 0.544,
    },
  },
  {
    name: 'Trust',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.474,
      accuracy: 0.716,
      sprayControl: 0.544,
      flicksControl: 0.432,
      nades: 0.69,
      tactics: 0.588,
    },
  },
  {
    name: 'Rapid',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.226,
      accuracy: 0.547,
      sprayControl: 0.635,
      flicksControl: 0.501,
      nades: 0.373,
      tactics: 0.537,
    },
  },
  {
    name: 'Laman',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.34,
      accuracy: 0.742,
      sprayControl: 0.377,
      flicksControl: 0.645,
      nades: 0.66,
      tactics: 0.835,
    },
  },
  {
    name: 'Obel1x',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.371,
      accuracy: 0.857,
      sprayControl: 0.892,
      flicksControl: 0.71,
      nades: 0.38,
      tactics: 0.519,
    },
  },
  {
    name: 'Point',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.329,
      accuracy: 0.597,
      sprayControl: 0.773,
      flicksControl: 0.892,
      nades: 0.753,
      tactics: 0.345,
    },
  },
  {
    name: 'Frame',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.259,
      accuracy: 0.428,
      sprayControl: 0.506,
      flicksControl: 0.576,
      nades: 0.473,
      tactics: 0.665,
    },
  },
  {
    name: 'Sc0pe',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.339,
      accuracy: 0.613,
      sprayControl: 0.478,
      flicksControl: 0.497,
      nades: 0.478,
      tactics: 0.409,
    },
  },
  {
    name: 'Luke',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.418,
      accuracy: 0.621,
      sprayControl: 0.448,
      flicksControl: 0.797,
      nades: 0.676,
      tactics: 0.305,
    },
  },
  {
    name: 'Force',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.265,
      accuracy: 0.737,
      sprayControl: 0.87,
      flicksControl: 0.33,
      nades: 0.628,
      tactics: 0.84,
    },
  },
  {
    name: 'Magnus',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.388,
      accuracy: 0.499,
      sprayControl: 0.449,
      flicksControl: 0.454,
      nades: 0.389,
      tactics: 0.715,
    },
  },
  {
    name: 'Apricity',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.331,
      accuracy: 0.843,
      sprayControl: 0.426,
      flicksControl: 0.715,
      nades: 0.347,
      tactics: 0.666,
    },
  },
  {
    name: 'Lamp',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.395,
      accuracy: 0.883,
      sprayControl: 0.891,
      flicksControl: 0.72,
      nades: 0.72,
      tactics: 0.843,
    },
  },
  {
    name: 'Hasky',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.475,
      accuracy: 0.696,
      sprayControl: 0.339,
      flicksControl: 0.8,
      nades: 0.59,
      tactics: 0.307,
    },
  },
  {
    name: 'Electricity',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.448,
      accuracy: 0.7,
      sprayControl: 0.803,
      flicksControl: 0.391,
      nades: 0.652,
      tactics: 0.331,
    },
  },
  {
    name: 'Anthony',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.307,
      accuracy: 0.667,
      sprayControl: 0.749,
      flicksControl: 0.807,
      nades: 0.524,
      tactics: 0.308,
    },
  },
  {
    name: 'Parson',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.324,
      accuracy: 0.565,
      sprayControl: 0.556,
      flicksControl: 0.573,
      nades: 0.508,
      tactics: 0.741,
    },
  },
  {
    name: 'Athos',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.404,
      accuracy: 0.657,
      sprayControl: 0.478,
      flicksControl: 0.832,
      nades: 0.457,
      tactics: 0.682,
    },
  },
  {
    name: 'Hans',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.396,
      accuracy: 0.493,
      sprayControl: 0.633,
      flicksControl: 0.527,
      nades: 0.345,
      tactics: 0.408,
    },
  },
  {
    name: 'Deirdre',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.496,
      accuracy: 0.466,
      sprayControl: 0.495,
      flicksControl: 0.42,
      nades: 0.605,
      tactics: 0.453,
    },
  },
  {
    name: 'Mirand',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.395,
      accuracy: 0.859,
      sprayControl: 0.337,
      flicksControl: 0.36,
      nades: 0.633,
      tactics: 0.759,
    },
  },
  {
    name: 'Edward',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.495,
      accuracy: 0.348,
      sprayControl: 0.677,
      flicksControl: 0.438,
      nades: 0.518,
      tactics: 0.892,
    },
  },
  {
    name: 'Panglosss',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.244,
      accuracy: 0.343,
      sprayControl: 0.353,
      flicksControl: 0.711,
      nades: 0.592,
      tactics: 0.534,
    },
  },
  {
    name: 'Romeo',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.275,
      accuracy: 0.823,
      sprayControl: 0.766,
      flicksControl: 0.872,
      nades: 0.497,
      tactics: 0.65,
    },
  },
  {
    name: 'Scapit',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.273,
      accuracy: 0.625,
      sprayControl: 0.561,
      flicksControl: 0.431,
      nades: 0.368,
      tactics: 0.514,
    },
  },
  {
    name: 'Halvard',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.431,
      accuracy: 0.569,
      sprayControl: 0.87,
      flicksControl: 0.48,
      nades: 0.894,
      tactics: 0.897,
    },
  },
  {
    name: 'Sutpen',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.324,
      accuracy: 0.727,
      sprayControl: 0.462,
      flicksControl: 0.341,
      nades: 0.786,
      tactics: 0.51,
    },
  },
  {
    name: 'Tarzan',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.297,
      accuracy: 0.448,
      sprayControl: 0.71,
      flicksControl: 0.588,
      nades: 0.467,
      tactics: 0.431,
    },
  },
  {
    name: 'Ol1ver',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.407,
      accuracy: 0.419,
      sprayControl: 0.337,
      flicksControl: 0.384,
      nades: 0.749,
      tactics: 0.652,
    },
  },
  {
    name: 'Weird',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.496,
      accuracy: 0.368,
      sprayControl: 0.405,
      flicksControl: 0.774,
      nades: 0.742,
      tactics: 0.417,
    },
  },
  {
    name: 'Zorro',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.31,
      accuracy: 0.85,
      sprayControl: 0.857,
      flicksControl: 0.86,
      nades: 0.536,
      tactics: 0.716,
    },
  },
  {
    name: 'Thomas',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.254,
      accuracy: 0.608,
      sprayControl: 0.413,
      flicksControl: 0.43,
      nades: 0.548,
      tactics: 0.835,
    },
  },
  {
    name: 'Shadow',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.312,
      accuracy: 0.318,
      sprayControl: 0.891,
      flicksControl: 0.634,
      nades: 0.556,
      tactics: 0.67,
    },
  },
  {
    name: 'Samuel',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.293,
      accuracy: 0.813,
      sprayControl: 0.351,
      flicksControl: 0.531,
      nades: 0.551,
      tactics: 0.7,
    },
  },
  {
    name: 'Oberon',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.291,
      accuracy: 0.424,
      sprayControl: 0.495,
      flicksControl: 0.459,
      nades: 0.894,
      tactics: 0.811,
    },
  },
  {
    name: 'Baron',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.294,
      accuracy: 0.654,
      sprayControl: 0.751,
      flicksControl: 0.379,
      nades: 0.859,
      tactics: 0.774,
    },
  },
  {
    name: 'Travis',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.213,
      accuracy: 0.629,
      sprayControl: 0.378,
      flicksControl: 0.65,
      nades: 0.483,
      tactics: 0.864,
    },
  },
  {
    name: 'Lochinvar',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.413,
      accuracy: 0.462,
      sprayControl: 0.511,
      flicksControl: 0.824,
      nades: 0.735,
      tactics: 0.784,
    },
  },
  {
    name: 'Cupper',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.47,
      accuracy: 0.421,
      sprayControl: 0.841,
      flicksControl: 0.586,
      nades: 0.451,
      tactics: 0.559,
    },
  },
  {
    name: 'Scout',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.286,
      accuracy: 0.495,
      sprayControl: 0.897,
      flicksControl: 0.869,
      nades: 0.846,
      tactics: 0.802,
    },
  },
  {
    name: 'TRex',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.42,
      accuracy: 0.888,
      sprayControl: 0.466,
      flicksControl: 0.848,
      nades: 0.418,
      tactics: 0.491,
    },
  },
  {
    name: 'BlackWater',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.333,
      accuracy: 0.326,
      sprayControl: 0.305,
      flicksControl: 0.622,
      nades: 0.555,
      tactics: 0.656,
    },
  },
  {
    name: 'Hard',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.267,
      accuracy: 0.818,
      sprayControl: 0.742,
      flicksControl: 0.506,
      nades: 0.724,
      tactics: 0.309,
    },
  },
  {
    name: 'Gozer',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.317,
      accuracy: 0.58,
      sprayControl: 0.597,
      flicksControl: 0.848,
      nades: 0.444,
      tactics: 0.538,
    },
  },
  {
    name: 'Pr0t0n',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.371,
      accuracy: 0.368,
      sprayControl: 0.539,
      flicksControl: 0.518,
      nades: 0.732,
      tactics: 0.651,
    },
  },
  {
    name: 'Argentum',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.273,
      accuracy: 0.587,
      sprayControl: 0.738,
      flicksControl: 0.864,
      nades: 0.348,
      tactics: 0.612,
    },
  },
  {
    name: 'Saxon',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.327,
      accuracy: 0.604,
      sprayControl: 0.86,
      flicksControl: 0.656,
      nades: 0.422,
      tactics: 0.523,
    },
  },
  {
    name: 'Conqueror',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.391,
      accuracy: 0.494,
      sprayControl: 0.473,
      flicksControl: 0.723,
      nades: 0.737,
      tactics: 0.649,
    },
  },
  {
    name: 'Aryan',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.389,
      accuracy: 0.359,
      sprayControl: 0.704,
      flicksControl: 0.716,
      nades: 0.811,
      tactics: 0.317,
    },
  },
  {
    name: 'ManGo',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.311,
      accuracy: 0.436,
      sprayControl: 0.623,
      flicksControl: 0.605,
      nades: 0.356,
      tactics: 0.396,
    },
  },
  {
    name: 'P1tcher',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.325,
      accuracy: 0.427,
      sprayControl: 0.358,
      flicksControl: 0.474,
      nades: 0.732,
      tactics: 0.678,
    },
  },
  {
    name: 'Catcher',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.317,
      accuracy: 0.587,
      sprayControl: 0.358,
      flicksControl: 0.387,
      nades: 0.703,
      tactics: 0.704,
    },
  },
  {
    name: 'Defender',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.318,
      accuracy: 0.459,
      sprayControl: 0.615,
      flicksControl: 0.791,
      nades: 0.739,
      tactics: 0.401,
    },
  },
  {
    name: 'Forward',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.232,
      accuracy: 0.884,
      sprayControl: 0.651,
      flicksControl: 0.339,
      nades: 0.449,
      tactics: 0.528,
    },
  },
  {
    name: 'Striker',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.472,
      accuracy: 0.327,
      sprayControl: 0.617,
      flicksControl: 0.883,
      nades: 0.393,
      tactics: 0.563,
    },
  },
  {
    name: 'Watchman',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.23,
      accuracy: 0.332,
      sprayControl: 0.762,
      flicksControl: 0.708,
      nades: 0.419,
      tactics: 0.523,
    },
  },
  {
    name: 'S1r',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.371,
      accuracy: 0.348,
      sprayControl: 0.633,
      flicksControl: 0.863,
      nades: 0.451,
      tactics: 0.515,
    },
  },
  {
    name: 'Flash',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.234,
      accuracy: 0.696,
      sprayControl: 0.453,
      flicksControl: 0.412,
      nades: 0.39,
      tactics: 0.404,
    },
  },
  {
    name: 'Ranger',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.319,
      accuracy: 0.836,
      sprayControl: 0.593,
      flicksControl: 0.589,
      nades: 0.633,
      tactics: 0.57,
    },
  },
  {
    name: 'Ginger',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.256,
      accuracy: 0.324,
      sprayControl: 0.321,
      flicksControl: 0.402,
      nades: 0.377,
      tactics: 0.858,
    },
  },
  {
    name: 'Rumor',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.272,
      accuracy: 0.713,
      sprayControl: 0.796,
      flicksControl: 0.74,
      nades: 0.618,
      tactics: 0.464,
    },
  },
  {
    name: 'Spark',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.27,
      accuracy: 0.324,
      sprayControl: 0.382,
      flicksControl: 0.482,
      nades: 0.543,
      tactics: 0.473,
    },
  },
  {
    name: 'Logan',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.383,
      accuracy: 0.634,
      sprayControl: 0.476,
      flicksControl: 0.374,
      nades: 0.5,
      tactics: 0.406,
    },
  },
  {
    name: 'Luke',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.496,
      accuracy: 0.658,
      sprayControl: 0.726,
      flicksControl: 0.885,
      nades: 0.445,
      tactics: 0.886,
    },
  },
  {
    name: 'Sawyer',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.307,
      accuracy: 0.894,
      sprayControl: 0.376,
      flicksControl: 0.341,
      nades: 0.543,
      tactics: 0.721,
    },
  },
  {
    name: 'Goliath',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.352,
      accuracy: 0.423,
      sprayControl: 0.358,
      flicksControl: 0.382,
      nades: 0.823,
      tactics: 0.822,
    },
  },
  {
    name: 'Beast',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.419,
      accuracy: 0.689,
      sprayControl: 0.874,
      flicksControl: 0.892,
      nades: 0.627,
      tactics: 0.351,
    },
  },
  {
    name: 'Brutus',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.405,
      accuracy: 0.765,
      sprayControl: 0.523,
      flicksControl: 0.797,
      nades: 0.317,
      tactics: 0.431,
    },
  },
  {
    name: 'Ares',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.263,
      accuracy: 0.808,
      sprayControl: 0.826,
      flicksControl: 0.345,
      nades: 0.871,
      tactics: 0.522,
    },
  },
  {
    name: 'Crusher',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.432,
      accuracy: 0.345,
      sprayControl: 0.699,
      flicksControl: 0.797,
      nades: 0.34,
      tactics: 0.738,
    },
  },
  {
    name: 'Magnum',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.424,
      accuracy: 0.828,
      sprayControl: 0.841,
      flicksControl: 0.813,
      nades: 0.642,
      tactics: 0.575,
    },
  },
  {
    name: 'Trigger',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.494,
      accuracy: 0.551,
      sprayControl: 0.487,
      flicksControl: 0.721,
      nades: 0.671,
      tactics: 0.868,
    },
  },
  {
    name: 'Atlas',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.482,
      accuracy: 0.378,
      sprayControl: 0.562,
      flicksControl: 0.686,
      nades: 0.462,
      tactics: 0.629,
    },
  },
  {
    name: 'Dragon',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.331,
      accuracy: 0.363,
      sprayControl: 0.743,
      flicksControl: 0.449,
      nades: 0.34,
      tactics: 0.652,
    },
  },
  {
    name: 'Talon',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.294,
      accuracy: 0.31,
      sprayControl: 0.859,
      flicksControl: 0.434,
      nades: 0.551,
      tactics: 0.504,
    },
  },
  {
    name: 'Ammo',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.396,
      accuracy: 0.6,
      sprayControl: 0.618,
      flicksControl: 0.798,
      nades: 0.606,
      tactics: 0.781,
    },
  },
  {
    name: 'Soldier',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.322,
      accuracy: 0.371,
      sprayControl: 0.568,
      flicksControl: 0.483,
      nades: 0.647,
      tactics: 0.511,
    },
  },
  {
    name: 'Chaos',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.349,
      accuracy: 0.68,
      sprayControl: 0.365,
      flicksControl: 0.64,
      nades: 0.852,
      tactics: 0.55,
    },
  },
  {
    name: 'Carbon',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'rifler',
      reaction: 0.493,
      accuracy: 0.774,
      sprayControl: 0.731,
      flicksControl: 0.745,
      nades: 0.724,
      tactics: 0.554,
    },
  },
  {
    name: 'Atom',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'sniper',
      reaction: 0.255,
      accuracy: 0.684,
      sprayControl: 0.869,
      flicksControl: 0.555,
      nades: 0.569,
      tactics: 0.877,
    },
  },
  {
    name: 'Secret',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'support',
      reaction: 0.418,
      accuracy: 0.724,
      sprayControl: 0.387,
      flicksControl: 0.895,
      nades: 0.769,
      tactics: 0.526,
    },
  },
  {
    name: 'Tractor',
    status: 'free',
    contract: {salary: 0, start: '', finish: ''},
    stat: {
      role: 'capitan',
      reaction: 0.302,
      accuracy: 0.597,
      sprayControl: 0.693,
      flicksControl: 0.686,
      nades: 0.702,
      tactics: 0.49,
    },
  },
];

export default freePlayersDefault;
