export default {
  MainPlayers: 'Main',
  BenchedPlayers: 'Benched',
  Settings: 'Settings',
  GlobalRating: 'Rating',
  Practice: 'Practice',
  Current: 'Current',
  Prize: 'Prize',
  Season: 'Season',
  Archived: 'Archived',
  TransferAgency: 'Transfer agency',
  YourTeam: 'Your team',
  Tournaments: 'Tournaments',
  More: 'More',
  Theme: 'Theme',
  Players: 'Players',
  Team: 'Team',
  MainRoaster: 'MainRoaster',
  Open: 'Open',
  NoBenchedPlayersYet: 'No benched players yet',
  NoActivePlayers: 'No active players',
  Role: 'Role',
  Contract: 'Contract',
  Salary: 'Salary',
  Reaction: 'Reaction',
  Accuracy: 'Accuracy',
  Flicks: 'Flicks',
  Spray: 'Spray',
  Nades: 'Nades',
  Tactics: 'Tactics',
  Aggression: 'Aggression',
  Stamina: 'Stamina',
  Individuals: 'Individuals',
};
