import {Gun} from '../interfaces/gunInterfaces';

type GunsData = Record<Gun['name'], Gun>;

const guns: GunsData = {
  // Pistols

  'Desert Eagle': {
    name: 'Desert Eagle',
    type: 'Pistol',
    price: 700,
    killAward: 300,
    inaccuracy: 6.2,
    fireRate: 267,
    damagePerSecond: 186,
    usedBy: 'T CT',
    damage: {
      withArmor: {
        head: 191,
        chestAndArms: 49,
        belly: 61,
        legs: 39,
      },
      withoutArmor: {
        head: 205,
        chestAndArms: 52,
        belly: 65,
        legs: 39,
      },
    },
  },
  'R8 Revolver': {
    name: 'R8 Revolver',
    type: 'Pistol',
    price: 600,
    killAward: 300,
    inaccuracy: 20,
    fireRate: 120,
    damagePerSecond: 83,
    usedBy: 'T CT',
    damage: {
      withArmor: {
        head: 319,
        chestAndArms: 79,
        belly: 99,
        legs: 64,
      },
      withoutArmor: {
        head: 343,
        chestAndArms: 85,
        belly: 107,
        legs: 64,
      },
    },
  },
  'Five-SeveN': {
    name: 'Five-SeveN',
    type: 'Pistol',
    price: 500,
    killAward: 300,
    inaccuracy: 11.1,
    fireRate: 400,
    damagePerSecond: 153,
    usedBy: 'CT',
    damage: {
      withArmor: {
        head: 115,
        chestAndArms: 28,
        belly: 37,
        legs: 23,
      },
      withoutArmor: {
        head: 126,
        chestAndArms: 31,
        belly: 39,
        legs: 23,
      },
    },
  },
  'Tec-9': {
    name: 'Tec-9',
    type: 'Pistol',
    price: 500,
    killAward: 300,
    inaccuracy: 6.9,
    fireRate: 500,
    damagePerSecond: 191,
    usedBy: 'T',
    damage: {
      withArmor: {
        head: 118,
        chestAndArms: 29,
        belly: 36,
        legs: 24,
      },
      withoutArmor: {
        head: 130,
        chestAndArms: 32,
        belly: 40,
        legs: 24,
      },
    },
  },
  'CZ75-Auto': {
    name: 'CZ75-Auto',
    type: 'Pistol',
    price: 500,
    killAward: 100,
    inaccuracy: 13.43,
    fireRate: 600,
    damagePerSecond: 200,
    usedBy: 'T CT',
    damage: {
      withArmor: {
        head: 95,
        chestAndArms: 53,
        belly: 29,
        legs: 23,
      },
      withoutArmor: {
        head: 123,
        chestAndArms: 30,
        belly: 38,
        legs: 23,
      },
    },
  },
  'Dual Berettas': {
    name: 'Dual Berettas',
    type: 'Pistol',
    price: 300,
    killAward: 300,
    inaccuracy: 9,
    fireRate: 120,
    damagePerSecond: 141,
    usedBy: 'T CT',
    damage: {
      withArmor: {
        head: 79,
        chestAndArms: 19,
        belly: 27,
        legs: 28,
      },
      withoutArmor: {
        head: 150,
        chestAndArms: 37,
        belly: 46,
        legs: 28,
      },
    },
  },
  P250: {
    name: 'P250',
    type: 'Pistol',
    price: 300,
    killAward: 300,
    inaccuracy: 11.1,
    fireRate: 400,
    damagePerSecond: 140,
    usedBy: 'T CT',
    damage: {
      withArmor: {
        head: 96,
        chestAndArms: 24,
        belly: 30,
        legs: 28,
      },
      withoutArmor: {
        head: 151,
        chestAndArms: 37,
        belly: 47,
        legs: 28,
      },
    },
  },
  'Glock-18': {
    name: 'Glock-18',
    type: 'Pistol',
    price: 200,
    killAward: 300,
    inaccuracy: 7.6,
    fireRate: 400,
    damagePerSecond: 80,
    usedBy: 'T',
    damage: {
      withArmor: {
        head: 56,
        chestAndArms: 14,
        belly: 17,
        legs: 22,
      },
      withoutArmor: {
        head: 119,
        chestAndArms: 29,
        belly: 37,
        legs: 22,
      },
    },
  },
  P2000: {
    name: 'P2000',
    type: 'Pistol',
    price: 200,
    killAward: 300,
    inaccuracy: 6.9,
    fireRate: 353,
    damagePerSecond: 94,
    usedBy: 'CT',
    damage: {
      withArmor: {
        head: 70,
        chestAndArms: 17,
        belly: 22,
        legs: 26,
      },
      withoutArmor: {
        head: 140,
        chestAndArms: 34,
        belly: 43,
        legs: 26,
      },
    },
  },
  'USP-S': {
    name: 'USP-S',
    type: 'Pistol',
    price: 200,
    killAward: 300,
    inaccuracy: 7.4,
    fireRate: 353,
    damagePerSecond: 94,
    usedBy: 'CT',
    damage: {
      withArmor: {
        head: 70,
        chestAndArms: 17,
        belly: 22,
        legs: 26,
      },
      withoutArmor: {
        head: 140,
        chestAndArms: 34,
        belly: 43,
        legs: 26,
      },
    },
  },

  // Rifles

  Galil: {
    name: 'Galil',
    type: 'Rifle',
    price: 1800,
    killAward: 300,
    inaccuracy: 9.37,
    fireRate: 667,
    damagePerSecond: 244,
    usedBy: 'T',
    damage: {
      withArmor: {
        head: 92,
        chestAndArms: 23,
        belly: 29,
        legs: 22,
      },
      withoutArmor: {
        head: 120,
        chestAndArms: 30,
        belly: 37,
        legs: 22,
      },
    },
  },
  'AK-47': {
    name: 'AK-47',
    type: 'Rifle',
    price: 2700,
    killAward: 300,
    inaccuracy: 7.01,
    fireRate: 600,
    damagePerSecond: 270,
    usedBy: 'T',
    damage: {
      withArmor: {
        head: 111,
        chestAndArms: 27,
        belly: 34,
        legs: 26,
      },
      withoutArmor: {
        head: 143,
        chestAndArms: 35,
        belly: 44,
        legs: 26,
      },
    },
  },
  'M4A1-S': {
    name: 'M4A1-S',
    type: 'Rifle',
    price: 2900,
    killAward: 300,
    inaccuracy: 5.5,
    fireRate: 600,
    damagePerSecond: 250,
    usedBy: 'CT',
    damage: {
      withArmor: {
        head: 92,
        chestAndArms: 26,
        belly: 33,
        legs: 28,
      },
      withoutArmor: {
        head: 132,
        chestAndArms: 37,
        belly: 47,
        legs: 28,
      },
    },
  },
  M4A4: {
    name: 'M4A4',
    type: 'Rifle',
    price: 2900,
    killAward: 300,
    inaccuracy: 5.5,
    fireRate: 667,
    damagePerSecond: 244,
    usedBy: 'CT',
    damage: {
      withArmor: {
        head: 92,
        chestAndArms: 23,
        belly: 28,
        legs: 24,
      },
      withoutArmor: {
        head: 131,
        chestAndArms: 32,
        belly: 41,
        legs: 24,
      },
    },
  },
  'SG 553': {
    name: 'SG 553',
    type: 'Rifle',
    price: 3000,
    killAward: 300,
    inaccuracy: 5.5,
    fireRate: 545,
    damagePerSecond: 263,
    usedBy: 'T',
    damage: {
      withArmor: {
        head: 119,
        chestAndArms: 29,
        belly: 37,
        legs: 22,
      },
      withoutArmor: {
        head: 119,
        chestAndArms: 29,
        belly: 37,
        legs: 22,
      },
    },
  },
  AUG: {
    name: 'AUG',
    type: 'Rifle',
    price: 3300,
    killAward: 300,
    inaccuracy: 5.4,
    fireRate: 600,
    damagePerSecond: 240,
    usedBy: 'CT',
    damage: {
      withArmor: {
        head: 100,
        chestAndArms: 25,
        belly: 31,
        legs: 21,
      },
      withoutArmor: {
        head: 112,
        chestAndArms: 28,
        belly: 35,
        legs: 21,
      },
    },
  },
  FAMAS: {
    name: 'FAMAS',
    type: 'Rifle',
    price: 2050,
    killAward: 300,
    inaccuracy: 10.45,
    fireRate: 667,
    damagePerSecond: 222,
    usedBy: 'CT',
    damage: {
      withArmor: {
        head: 84,
        chestAndArms: 21,
        belly: 26,
        legs: 22,
      },
      withoutArmor: {
        head: 120,
        chestAndArms: 30,
        belly: 37,
        legs: 22,
      },
    },
  },

  // Sniper Rifles

  AWP: {
    name: 'AWP',
    type: 'Sniper Rifle',
    price: 4750,
    killAward: 100,
    inaccuracy: 2.2,
    fireRate: 41,
    damagePerSecond: 76,
    usedBy: 'T CT',
    damage: {
      withArmor: {
        head: 448,
        chestAndArms: 112,
        belly: 140,
        legs: 85,
      },
      withoutArmor: {
        head: 459,
        chestAndArms: 115,
        belly: 143,
        legs: 85,
      },
    },
  },
  'SSG 08': {
    name: 'SSG 08',
    type: 'Sniper Rifle',
    price: 1700,
    killAward: 300,
    inaccuracy: 3.23,
    fireRate: 48,
    damagePerSecond: 58,
    usedBy: 'T CT',
    damage: {
      withArmor: {
        head: 229,
        chestAndArms: 74,
        belly: 93,
        legs: 66,
      },
      withoutArmor: {
        head: 352,
        chestAndArms: 88,
        belly: 110,
        legs: 66,
      },
    },
  },
  'SCAR-20': {
    name: 'SCAR-20',
    type: 'Sniper Rifle',
    price: 5000,
    killAward: 300,
    inaccuracy: 2.3,
    fireRate: 240,
    damagePerSecond: 256,
    usedBy: 'CT',
    damage: {
      withArmor: {
        head: 263,
        chestAndArms: 65,
        belly: 82,
        legs: 59,
      },
      withoutArmor: {
        head: 319,
        chestAndArms: 79,
        belly: 99,
        legs: 59,
      },
    },
  },
  G3SG1: {
    name: 'G3SG1',
    type: 'Sniper Rifle',
    price: 5000,
    killAward: 300,
    inaccuracy: 2.3,
    fireRate: 240,
    damagePerSecond: 256,
    usedBy: 'T',
    damage: {
      withArmor: {
        head: 263,
        chestAndArms: 65,
        belly: 81,
        legs: 60,
      },
      withoutArmor: {
        head: 316,
        chestAndArms: 79,
        belly: 98,
        legs: 60,
      },
    },
  },
};

export default guns;
